"""
Список моделей для генератора фото WB.
Сгенерировано автоматически из wb_cards_v3.xlsx.

GLOSS_AND_ANTI — модели, для которых есть И глянцевое, И антишпион стекло (6 фото: 3 кол-ва × 2 типа)
GLOSS_ONLY    — модели, для которых есть ТОЛЬКО глянцевое стекло (3 фото: 3 кол-ва × 1 тип)
"""

GLOSS_AND_ANTI = [
    'Honor 200 Lite',
    'Honor 200 Smart',
    'Honor 400 Lite',
    'Honor 400 Smart',
    'Honor 600 Smart',
    'Honor 90 Lite',
    'Honor 90 Smart',
    'Honor X5B Plus',
    'Honor X7C',
    'Honor X7D',
    'Honor X8B',
    'Honor X8C',
    'Honor X8D',
    'Huawei Nova 14',
    'Huawei Pura 70',
    'Huawei Pura 80',
    'Infinix Hot 70',
    'Infinix Note 50 4G',
    'Infinix Note 50 Pro 4G',
    'Infinix Note 50 Pro+',
    'Infinix Smart 10',
    'Infinix Smart 20',
    'Infinix Smart 9',
    'Motorolla Moto G86',
    'Motorolla Moto G86 Power',
    'OnePlus Ace 6 Ultra',
    'OnePlus Nord 6',
    'OnePlus Nord CE6',
    'OnePlus Nord CE6 Lite',
    'OnePlus Turbo 6',
    'OnePlus Turbo 6V',
    'OnePlus Turbo 6X',
    'OnePlus Turbo 6X Pro',
    'Oppo K15 Pro+',
    'Realme C67',
    'Realme C75',
    'Redmi Note 15 Pro 5G',
    'Samsung Galaxy A05',
    'Samsung Galaxy A06',
    'Samsung Galaxy A16',
    'Samsung Galaxy A17',
    'Samsung Galaxy A27',
    'Samsung Galaxy A56',
    'Samsung Galaxy M16',
    'Samsung Galaxy M17e',
    'Samsung Galaxy M55',
    'Samsung Galaxy M56',
    'Samsung Galaxy S24FE',
    'Samsung Galaxy S25FE',
    'Tekno Spark 30 Pro',
    'Tekno Spark 30C',
    'Xiaomi Redmi A5'
]


GLOSS_ONLY = [
    'Honor 500 Smart',
    'Honor 600 Lite',
    'Honor 600e',
    'Honor Play 11 Plus',
    'Honor Play 70C',
    'Honor Play 80',
    'Honor Play 80 Plus',
    'Honor Play 80 Pro',
    'Honor Play10',
    'Honor X5d',
    'Honor X5d Plus',
    'Honor X7e',
    'Honor X80i',
    'Huawei Enjoy 90',
    'Huawei Enjoy 90m Plus',
    'Huawei Pura 90',
    'Huawei Pura 90 Pro',
    'Huawei Pura 90 Pro Max',
    'Huawei enjoy 90 Pro Max',
    'Huawei nova 15',
    'Huawei nova 15 Max',
    'Huawei nova 15 Pro',
    'Huawei nova 15 Ultra',
    'Huawei nova 16 Pro',
    'Huawei nova 16 Ultra',
    'Huawei nova Y74',
    'Infinix GT 50 Pro',
    'Infinix Note 60',
    'Infinix Note 60 Pro',
    'Infinix Note 60 Ultra',
    'Motorola Moto G Max',
    'Motorola Moto G47',
    'Motorola Moto G87',
    'Nothing Phone (4a)',
    'Nothing Phone (4a) Pro',
    'OnePlus 15R',
    'Oppo Find X9s',
    'RugOne Xever 8',
    'Tecno Camon 50 4G',
    'Umidigi A75x',
    'Umidigi G100 Pro',
    'Umidigi G100x',
    'Xiaomi 15T',
    'Xiaomi 17 Max',
    'Xiaomi 17 Ultra',
    'Xiaomi 17T',
    'Xiaomi 17T Pro',
    'Xiaomi Poco C81',
    'Xiaomi Poco C81 Pro',
    'Xiaomi Poco C81x',
    'Xiaomi Poco X8 Pro Max',
    'Xiaomi Redmi 15a',
    'Xiaomi Redmi A7',
    'Xiaomi Redmi A7 Pro 4G',
    'Xiaomi Redmi K90 Max',
    'Xiaomi Redmi R70',
    'Xiaomi Redmi R70m',
    'Xiomi Poco X8 Pro'
]
